# CD pipeline for Next JS for development branch

name: Next JS CD -- development

on:
  push:
    branches:
      - develop

jobs:
  docker-build-and-push:
    name: Docker build image and push
    runs-on: ubuntu-latest
